### ISSUE TITLE
dataset pls

### ISSUE THREAD

**Issue by ehfo0** [Nemzy/video_generator#1]
Hi 
thanks for sharing ur code! 
it's amazing!
would u pls upload the dataset as well pls?
I really like to run it on mp PC! pls!
`train_ds, valid_ds = read_dataset('data/frames', test_size = 0.097)`

`\data_utils.py in read_dataset(path, test_size) 58 def read_dataset(path, test_size): 59 '''Creates data set''' ---> 60 dirpath, dirnames, filenames = next(os.walk(path)) 61 images = read_images([os.path.join(dirpath, filename) for filename in filenames]) 62 images = np.array(images, dtype = np.float32) StopIteration: #1`

**Comment by Nemzy** [comment]
@ehfo0 Sure, will do today.

**Comment by ehfo0** [comment]
Thanks :)

**Comment by Nemzy** [comment]
@ehfo0 Done. I haven't finished the project yet, hope I will have time to finish it. README now also includes steps for dataset creation if you want to create your own.

**Comment by ehfo0** [comment]
@Nemzy Thank U really much! 
now I can generate any video! I LOVE it!
